### ISSUE TITLE
Documentation about Persistence

### ISSUE THREAD

**Issue by SEJeff** [mesos/kafka#100]
Many other frameworks use HDFS for data persistence, this framework doesn't have any mentions of HDFS, so I was curious how the persistence works? Is it currently deployed using a shared SAN?

The docs in `README.md` mention that the framework will attempt to restart the broker on the same node if it fails. Is this framework using the persistent reservation features in Mesos 0.23?

**Comment by joestein** [comment]
@SEJeff take a look at how to change the location of the data stored in Kafka https://github.com/mesos/kafka#changing-the-location-of-data-stored you can use local storage so the data sits outside the sandbox on local disk. The scheduler has stickiness https://github.com/mesos/kafka#broker-placement-stickiness feature to keep it going back to where the data is unless surpassing acceptable failure.  

We have plans to include support for new 0.23 features, yes. Including dynamic reservations https://github.com/mesos/kafka/issues/102 and also support persistent storage https://github.com/mesos/kafka/issues/104 though neither is required to reliably run Kafka on Mesos.

**Comment by SEJeff** [comment]
Right, this is more for documentation on it :)

Speaking of, will you be at MesosCon? I'm leaving tonight and would love to pick your brains over :beers: on it.
