### ISSUE TITLE
Build tests fail if port 8000 in use

### ISSUE THREAD

**Issue by ejether** [mesos/kafka#106]
Not really an issue, but it stumped me for a a bit and It would be nice to have a note in the docs or have a check.

Full story:
I've got python SimpleHTTPServer running on port 8000 on the VM that I was trying to do the `./gradlew jar` and the build fails while it is running

**Comment by dmitrypekar** [comment]
Hi @ejether 
Thank you for your feedback.
Tests using HttpServer on 8000 fixed to use port 0 (any available);
Test using ZkServer modified to use 56789 (less probable) port instead of 8000,
cause I0Itec ZkServer doesn't support binding on 0.
