### ISSUE TITLE
Help For runing Spark Word Count 

### ISSUE THREAD

**Issue by monukhamba** [mesos/kafka#110]
I get the folowwing error when I have the scheduler running and I try to run a wordcount with spark

root@mesos2 spark-source]# bin/run-example org.apache.spark.examples.streaming.JavaKafkaWordCount mesos1.xxx.com:2181,mesos2.xxx.com:2181,mesos3.xxx.com:2181/  my-consumer-group topic1,topic2 1
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
15/08/27 23:34:01 INFO StreamingExamples: Setting log level to [WARN] for streaming example. To override add a custom log4j.properties to the classpath.
## Time: 1440718446000 ms

15/08/27 23:34:07 WARN AppInfo$: Can't read Kafka version from MANIFEST.MF. Possible cause: java.lang.NullPointerException
15/08/27 23:34:07 WARN RangeAssignor: No broker partitions consumed by consumer thread my-consumer-group_mesos2.xxx.com-1440718447239-15350409-0 for topic topic2
## Time: 1440718448000 ms

---
## Time: 1440718450000 ms

---
## Time: 1440718452000 ms

---

**Comment by dmitrypekar** [comment]
Could you please clarify how this is related to kafka-mesos project?
If this ticket is created by mistake, please close it.

**Comment by monukhamba** [comment]
It's not a bug , needed help if you guys could provide some inputs

**Comment by dmitrypekar** [comment]
closing as expired and not related to project
