### ISSUE TITLE
Possible to switch existing cluster to use kafka framework without downtime?

### ISSUE THREAD

**Issue by mindscratch** [mesos/kafka#116]
Is it possible to switch an existing Kafka cluster to use the kafka framework with zero downtime?

**Comment by joestein** [comment]
The brokers that the schedulers start up are against a zk host:port/path so as long as that is the same as the brokers that you want to migrate from then they would all be one cluster (some managed by scheduler and some not) from kafka brokers perspective.

As far as zero downtime, it is possible. It doesn't really have anything related to the scheduler or even mesos at that point https://kafka.apache.org/documentation.html#basic_ops_cluster_expansion is what to look into for that.

**Comment by mindscratch** [comment]
thanks
