### ISSUE TITLE
Framework runs out of memory when run in a docker container via marathon

### ISSUE THREAD

**Issue by mindscratch** [mesos/kafka#117]
I've deployed the kafka framework on Mesos 0.23, using Marathon 0.9 and docker 1.7.1 on CentOS 7. Initially I gave the container 256MB of memory ([based on this](https://github.com/mesos/kafka/tree/master/src/docker#running-image-in-marathon)). 

On a cluster with ~100 slaves, I observed it quickly ran out of memory and the container was killed. Increasing the memory to 2GB, helps (after 30minutes docker stats reports that the container is using ~750MB), but I'm curious if there is some way to better gauge how much memory it might need based on the number of slaves, or perhaps there's a memory leak.

**Comment by joestein** [comment]
There are a bunch of more reasonable defaults for not just simple local testing that can be updated in the README and some of the other configurations and settings, agreed.

**Comment by dmitrypekar** [comment]
Perhaps, this is highly dependent on the broker's usage scenario. If deploying on prod, you, probably, should consult kafka-related docs, stating about recommended heap settings.
