### ISSUE TITLE
scheduler restarts when rebalance is invoked or status call for rebalance is invoked

### ISSUE THREAD

**Issue by vidhyaarvind** [mesos/kafka#121]
Seen multiple instances of this happening. I had increased scheduler memory from 1024 to 2048 and still this issue persists. I don't see any kill message in scheduler logs when this happens. 

Rebalance is triggered and I see 504 bad gateway(since I have a proxy before the curl) in my curl and I see scheduler restarting. Even rebalance status calls restarts the scheduler. 

I run other operations like broker add/topic add using curl and I don't see this happening.

**Comment by dmitrypekar** [comment]
Hi @vidhyaarvind 
Suppose, that this issue is already fixed indirectly and is not actual anymore. Please comment on this, if the problem still happens. If not, will close this ticket in 10 days.

**Comment by dmitrypekar** [comment]
Closing the ticket as outdated. I haven't seen the problem any more.
