### ISSUE TITLE
Framework requires "unzip" 

### ISSUE THREAD

**Issue by keithchambers** [mesos/kafka#125]
Some customers running DCOS (Mesos) on RHEL7 have run in to an issue where deployment fails because unzip is not installed.  Our thinking at Mesosphere is that tar is more universal than unzip and would be a better alternative.

This is being tracked inside Mesosphere at JIRA: https://mesosphere.atlassian.net/browse/DCOS-3206

**Comment by joestein** [comment]
There are artifacts posted also for tar https://github.com/mesos/kafka/releases/tag/v0.9.2.0 not sure what artifact is exactly having an unzipping problem?

**Comment by dmitrypekar** [comment]
The only artifact using zip (in DCOS) is jre:
https://s3-us-west-2.amazonaws.com/kafka-mesos/jre-7-openjdk.zip

Probably, we need to tar.gz it and post a PR to the universe project.

## 

BR
Dmitry Pekar

**Comment by dmitrypekar** [comment]
Updated jre on S3 to use tgz instead of zip:
https://d1vubr0evspla.cloudfront.net/jre-7u79-openjdk.tgz

Changes available in PR - https://github.com/mesosphere/universe/pull/235
Will be fixed after the merge.

## 

BR
Dmitry

**Comment by dmitrypekar** [comment]
Probably we also need to correct help. `help scheduler` mentions:

```
--jre                JRE zip-file (jre-7-openjdk.zip). Default - none.
```

Which could be actually tgz or zip.

**Comment by joestein** [comment]
https://github.com/mesosphere/universe/pull/235 is merged now, thanks!
