### ISSUE TITLE
The executor heap isn't getting set

### ISSUE THREAD

**Issue by joestein** [mesos/kafka#137]
We set the heap for starting the broker https://github.com/mesos/kafka/blob/master/src/scala/ly/stealth/mesos/kafka/Scheduler.scala#L36-L38 however by that time the executor is already running. We need to also set the heap in the JAVA_OPTS so the executor has a bounds above what the broker is getting. This looks like a good mechanism for this https://github.com/mesos/logstash/blob/master/logstash-scheduler/src/main/java/org/apache/mesos/logstash/config/ExecutorEnvironmentalVariables.java#L36-L39 to utilize adapted some.

**Comment by dmitrypekar** [comment]
Hi @joestein 

Let me clarify on this:
1. for now Scheduler doesn't share/pre-fork Executor for running broker. The Executor is started and stopped just in the same moment as Broker does;
2. for now Broker and Executor are executed in the same JVM process. That means, than we need a single mem & heap setting for both (as is now);

May be I am missing something, in that case could you please explain the probelm in more details (we can use Skype for that)

**Comment by dmitrypekar** [comment]
@joestein 
Joe, could you please comment on this?
Imho, this ticket contains not actual information ..
