### ISSUE TITLE
Not able to kafka/mesos as service in marathon, recieving following error

### ISSUE THREAD

**Issue by rsingh2411** [mesos/kafka#140]
I am trying to run kafka/mesos as  amarathon service , its is giving following error.
I was able to run the docker image independantly on the slave though
I1019 21:57:38.620918  6590 exec.cpp:134] Version: 0.25.0
I1019 21:57:38.625092  6592 exec.cpp:208] Executor registered on slave 20151016-200105-1929488576-5050-16853-S1
cannot enable tty mode on non tty input
sh: 2: --master=master:5050: not found

**Comment by joestein** [comment]
master is the default property for hostname of sample master server, you should change that to what works (and really should be using zk)

**Comment by rsingh2411** [comment]
I was using the following command 

sudo docker run -t -p 5900:5900 --add-host=master:192.168.1.115 root/kafka-mesos ./kafka-mesos.sh scheduler --master=master:5050 --zk=192.168.1.115:2181 --api=http://192.168.1.118:5900 --storage=zk:/kafka-mesos --log=/var/log/mesos.log --debug=true
when running with -it i am recieiving above mentioned error
however when i remove  i option then error is not seen and scheduler comes up nicely
