### ISSUE TITLE
Allow retrieving broker logs via the api

### ISSUE THREAD

**Issue by SEJeff** [mesos/kafka#143]
Interesting user request from a consumer of this framework. They love the api and the consistency. Would it be possible to build in rudimentary support for retrieving / viewing the logs for a given broker from the API?

If you disagree, feel free to close it, but this seems like a really nice user story

**Comment by joestein** [comment]
There are much better way to facilitate that especially with a lot of logs. The scheduler will never be able to keep with such large volumes unless it is only giving you the last snippet. 

Typically folks do something like https://github.com/stealthly/java-kafka and ship logs to Kafka broker topic itself, from there you can do anything you want with them.

I don't get the use case for the logs through the API but if you can expand behind the problem you are trying to solve we can figure what might be the best solutions.

**Comment by SEJeff** [comment]
Hi @joestein I'm open to other options certainly and literally just reiterated what was requested of me. The users requested a straightforward way for them to get the kafka broker logs. They're setting various broker options and whatnot and want to be able to monitor the logs as they're testing this new kafka based system. They are mostly ignorant of the fact that it runs on mesos, or of mesos in general. They love the REST api this framework provides and to them it is just "magic TM".

Their end user request is simply a simple way to get ahold of the logs. Perhaps you could provide a way to get the exact url of the sandbox directory the slave provides from the api or something?

How would you ship the logs from individual mesos tasks running these brokers into kafka? I suspect that is certainly one way to do it, but when you're putting the logs used to potentially monitor kafka into kafka, that seems a bit meta.

**Comment by dmitrypekar** [comment]
Really interesting feature request. Perhaps we can provide a REST and CLI for that like `./kafka-mesos.sh broker log 0 --lines=1000` (print 1000 recent lines of log for broker 0). Potentially this could more handy for the end-user compared to browsing into Mesos sandbox.

**Comment by SEJeff** [comment]
@dmitrypekar Something like that is precisely what I was thinking. I don't think this is meant for a live streaming realtime log tool. Just a way to get some of the broker logs for verification and debugging.

This is the only serious feature I see (from a user standpoint) missing from this framework. Nicely done btw!
