### ISSUE TITLE
Dynamic Reservations break the scheduler

### ISSUE THREAD

**Issue by sargun** [mesos/kafka#145]
So, I’ve been testing with the Kafka framework - dynamic reservations - they were breaking the master version of the Kafka scheduler - the Kafka scheduler opportunistically accepts them because at the moment, they’re indiscernible from static reservations, but if you try to use them without setting the principal, things go awry.

I'm working on a solution in the persistence branch to this.

**Comment by dmitrypekar** [comment]
@sargun can you please check this against new release 0.9.3.0 (in which --volume support is added)?
If it not happens anymore, can you plz close this ticket?
