### ISSUE TITLE
Why don't brokers store zk nodes under --storage of scheduler?

### ISSUE THREAD

**Issue by memelet** [mesos/kafka#151]
When I start the scheduler with --storage zk:/kafka-mesos it creates and uses that node. But after I start brokers they create nodes at the root:

/controller
/controller_epoch
/brokers
/admin
/consumers
/config

Am I missing some configuration that would keep these under the --storage node?

[kafak-mesos v0.9.2.0]

**Comment by sargun** [comment]
You have to set the --zk flag for this.

**Comment by memelet** [comment]
The zk flag on scheduler?

```
--zk                 Kafka zookeeper.connect. Examples:
                      - master:2181
                      - master:2181,master2:2181
```

I do set that when starting the scheduler, but its the host:port of zookeeper. What does that have to do with the node hierarchy/namespace?

**Comment by joestein** [comment]
```
--zk host:port/path
```

This is another flag on purpose so the brokers have separation of concern from the zk cluster than the scheduler and mesos use (if/when desired, then could be same for testing/dev/etc)

**Comment by memelet** [comment]
So set the --zk host:port/path on broker add?

   $ ./kafka-mesos.sh broker add --zk host:port/path 0   

Or do you mean just add the /path the --zk of the scheduler along with --storage ?

(I will try both, or look in the code)

**Comment by memelet** [comment]
Ok, got it:

--zk host:port/path  defines the top level node for the scheduler and brokers
--storage  defines the node under above for just the scheduler

thanks!!
