### ISSUE TITLE
gradle jar fails with java 8

### ISSUE THREAD

**Issue by utgarda** [mesos/kafka#152]
etsvigun@ip-172-31-37-254:~/devenv/kafka$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
etsvigun@ip-172-31-37-254:~/devenv/kafka$ ./gradlew jar
...
ly.stealth.mesos.kafka.ExprTest > expandBrokers_sortByAttrs FAILED
    java.lang.AssertionError at ExprTest.scala:99

**Comment by dmitrypekar** [comment]
Hi @utgarda, 
Thanks for a feedback.
Fixed in master branch.
