### ISSUE TITLE
Confused about init()'s dir.startsWith("kafka")

### ISSUE THREAD

**Issue by memelet** [mesos/kafka#156]
```
    private def init(): Unit = {
      // find kafka dir
      for (file <- new File(".").listFiles())
        if (file.isDirectory && file.getName.startsWith("kafka"))
          dir = file

      if (dir == null) throw new IllegalStateException("Kafka distribution dir not found")
      ...
   }
```

I'm not quite sure what I have changed in my install, but now brokers fail to start because the kafka directory looks like:

Create via Ansible for running command line:

```
[barry@s-mesos-master-1]/opt/kafka/0.9.2.0-61❯ ll
total 31M
drwxr-xr-x 5 root   root   4.0K Feb 26  2015 kafka_2.10-0.8.2.1
-rw-r--r-- 1 consul consul  16M Mar  9  2015 kafka_2.10-0.8.2.1.tgz
-rw-r--r-- 1 consul consul  16M Nov 14 08:51 kafka-mesos-0.9.1.4.jar
-rwxr-xr-x 1 consul consul  363 Nov 18 07:07 kafka-mesos.sh
```

Created via Marathon in Mesos sandbox:

```
-rwxr-xr-x  1   root    root    307 B   Nov 11 13:03     kafka-mesos.sh  Download
-rw-r--r--  1   root    root    15 MB   Nov 14 14:21     kafka-mesos-0.9.1.4.jar     Download
-rw-r--r--  1   root    root    29 MB   Nov 18 12:37     kafka-mesos-0.9.2.0-61.tgz  Download
-rw-r--r--  1   root    root    15 MB   Mar 09 23:59     kafka_2.10-0.8.2.1.tgz  Download
-rw-r--r--  1   root    root    7 KB    Nov 18 12:42     stderr  Download
-rw-r--r--  1   root    root    4 KB    Nov 18 12:42     stdout  Download
```

(as an aside, the kafka-mesos jar is 0.9.1.4 because its hard coded to that gradle, its
really 0.9.2.0)

So when I try to start a broker I get

```
Caused by: java.lang.IllegalStateException: Kafka distribution dir not found
```

I am really confused because I had brokers running the other day and as far as I can tell
I have not changed how I deploy (other than to add the path to the --zk argument).

When this error is thrown, is it from the actual scheduler process already running on mesos?
Or is the from the code in the /opt/kafka directory from which I ran mesos-kafka.sh broker start?
Well, I'm guessing the former, since the latter indeed has a directory starting with 'kafka'.
But then how could this have ever worked if mesos does not expand nested *.tgz files?

**Comment by memelet** [comment]
Ok, I figured this out. I am deploying via marathon, and marathon leaves the .tgz it downloads in the sandbox next to the extracted files. The scheduler when serving the kafka*.tgz deployment package searches for the .tgz like:

```
  // HttpServer.scala
  private def resolveDeps: Unit = {
    val jarMask: String = "kafka-mesos.*\\.jar"
    val kafkaMask: String = "kafka.*\\.tgz"

    for (file <- new File(".").listFiles()) {
      if (file.getName.matches(jarMask)) jar = file
      if (file.getName.matches(kafkaMask)) kafkaDist = file
    }
    ...
```

So it was finding the kafka-mesos-*.tgz instead fo kafka_2.10-0.8.2.1.tgz.

This way of selecting files seems quite brittle. Easy to deal with once you know what's going on. But still, it cost me most of a day.

**Comment by dmitrypekar** [comment]
hi @memelet 
Thank you for your feedback. To my mind, this is a good default behavior. Of course, we can provide CLI options to override this (to be able to specify `kafka\*.tgz` strictly). Unfortunately, I do not see a better way for a default resolution mechanism to find `kafka*.tgz` and `kafka dir`. If you have some ideas about that, please comment on this ticket.

**Comment by memelet** [comment]
I agree, without having to specify lots of extra arguments a convention like this is workable. Probably just a mention in the documentation. Maybe in a section for deploying via marathon when not using docker the warns off using a tgz starting with kafka.
