### ISSUE TITLE
Why does the Scheduler need to be run in HOST mode when inside a Docker container?

### ISSUE THREAD

**Issue by aglahe** [mesos/kafka#157]
Based upon what i learned from #155, setting up the scheduler in HOST mode fixed that issue...but why?  What is the communication path between the Scheduler and the Tasks?  Are there ports that need to be open between them other than 7000?

It looks like you can run the scheduler in BRIDGE mode..when run outside of marathon..but, for some reason, the fix for #155 was to put it in HOST mode.

Just curious.

Thanks in advance.

**Comment by dmitrypekar** [comment]
Afaik, Scheduler communicates with mesos master via 2 connections:
1. from scheduler to master;
2. from master to scheduler;
So scheduler should be accessible from master. I think was the point.
