### ISSUE TITLE
NullPointerException in Scheduler$.onBrokerStopped

### ISSUE THREAD

**Issue by sjoerdmulder** [mesos/kafka#159]
Trying to get it running but somehow it keeps crashing:
Using latest version 0.9.3.0

```
2015-11-19 16:41:04,760 [Thread-15] INFO  ly.stealth.mesos.kafka.Scheduler$  - [resourceOffers]
sgnt-test1#70963 cpus:3.80; mem:6470.00; disk:221022.00; ports:[31000..31217][31219..31729][31731..32000]
sgnt-test3#70964 cpus:3.40; mem:6470.00; disk:221022.00; ports:[31000..31119][31121..31244][31246..31790][31792..32000]
sgnt-test2#70965 cpus:3.90; mem:6726.00; disk:221022.00; ports:[31000..31385][31387..32000]
test#70966 cpus:0.90; mem:5764.00; disk:918506.00; ports:[31000..31533][31535..31843][31845..31943][31945..32000] public:true
2015-11-19 16:41:04,825 [Thread-17] INFO  ly.stealth.mesos.kafka.Scheduler$  - [statusUpdate] broker-1-0e913403-e330-4906-b0d6-649ba74706d7 TASK_FINISHED slave:#f6-S1 reason:REASON_COMMAND_EXECUTOR_FAILED
Exception in thread "Thread-17" java.lang.NullPointerException
    at ly.stealth.mesos.kafka.Scheduler$.onBrokerStopped(Scheduler.scala:221)
    at ly.stealth.mesos.kafka.Scheduler$.onBrokerStatus(Scheduler.scala:198)
    at ly.stealth.mesos.kafka.Scheduler$.statusUpdate(Scheduler.scala:120)
I1119 16:41:04.829921    36 sched.cpp:1805] Asked to abort the driver
I1119 16:41:04.830366    36 sched.cpp:1070] Aborting framework '7c1eca31-281f-4f4a-a24e-63c0c2ac89f6-0173'
```

**Comment by dmitrypekar** [comment]
Hi @sjoerdmulder 

This is very strange situation. It seems that Scheduler got status update for unexistent Broker.
Could you please provide following additional info:
1. What caused the broker to stop: manual stop or failure;
2. In case of failure could you please provide executor logs (from sandbox via web ui);
3. Did you delete those broker manually via CLI or REST ?;
4. Do you have a strict scenario to reproduce this error?

Thank you for your feedback.

**Comment by sjoerdmulder** [comment]
I was playing around with docker + starting mesos-kafka multiple times (and stopping them). So there is now a  list of 10+ kafka schedulers in mesos `Framework` that don't exist anymore? (probally because of the framework-timeout set to 30days?) But shouldn't it reregister instead of creating a new one?

I stopped one broker manually using the REST API (actually using the Kafka Manager + Mesos fixes) and actually killed a scheduler (`kill -9` style) because i lost the terminal, which had 1 still broker running, which i in return also killed :)

So now if have 2 active tasks in Mesos that are brokers.

```
broker-1-0e913403-e330-4906-b0d6-649ba74706d7   broker-1    FINISHED    2015-11-19T17:26:05+0100
broker-1-d13e5b5b-fdc5-4c8f-8725-9658bda2cf11   broker-1    LOST    2015-11-18T17:13:02+0100
```

Don't know how to reproduce this all (lot of playing around) but would like to know how i can get it back into a heatlhy system again.

**Comment by dmitrypekar** [comment]
Ok. First of all, Scheduler stores state in a json file or zookeeper node. Based on that state it restores its configuration (broker list and settings) after restart. If those file is gone, a new framework would be registered.

You should terminate all inactive schedulers via `POST http://master:5050/teardown` REST api call to Master. After that all orphan brokers (if exist) would be terminated. If you are using docker or marathon please use also Zookeeper to store Scheduler's state. That would allow restarting the scheduler from the point there it has been left before shutdown.

I think I understood how this problem did happen and will provide a fix for it. But it is ok for you to continue to use 0.9.3.0

**Comment by dmitrypekar** [comment]
Problem with NullPointerException fixed in master.

**Comment by sjoerdmulder** [comment]
Yes no problem to keep using 0.9.3.0. I'm using Marathon with Zookeeper config now to run it. By default it was using the file but in combination with docker thats not a great combination :smiling_imp: 

Will clear the mesos frameworks, Thnx!
