### ISSUE TITLE
Control Kafka with scheduler api endpoint

### ISSUE THREAD

**Issue by tpolekhin** [mesos/kafka#164]
Hello, 

It would be really much easier to spawn a `kafka-scheduler` with `marathon`, and then control brokers and topics with direct `curl` requests to `scheduler` api endpoint, without using `.jar`, like this:
`curl -XPOST http://kafka-scheduler:port/broker/add -d '{JSON parameters}'`

Do you plan to implement such thing? Or maybe it is possible, but i didn't find any documentation regarding this.

**Comment by dmitrypekar** [comment]
Actually README.md at project root contains an information about REST api.
You can use it to control Scheduler. Please close the ticket if this answers your question.

**Comment by tpolekhin** [comment]
@dmitrypekar oh my god, thats embarrassing :)
thank you, and sorry :)

**Comment by tpolekhin** [comment]
@dmitrypekar i think this:
`val jvmOptions: String = request.getParameter("jvmOptions")`
should be described in readme, because of different key from `jvm-options` in `kafka-mesos.sh`
