### ISSUE TITLE
cmd in JSON file seems to assume 'master' is mapped to an ip address

### ISSUE THREAD

**Issue by batwicket** [mesos/kafka#171]
Probably a misunderstanding on my part, since I'm quite new to this, but when i try to launch the scheduler via the JSON file described at https://github.com/mesos/kafka/tree/master/src/docker#running-image-in-marathon the marathon framework complains that it cannot find a resource satisfying the constraint that the hostname is like "master". Is there something i'm missing? There is a clear assignment to master on the docker command line in the previous section. I should probably add that the hostname passed in the offer to marathon is the id of the slave host.. not an IP address or an english string.

**Comment by batwicket** [comment]
I've tried it on playa and minimesos and the same issue occurs. It works if the constraint is removed, but then i run into another issue:
Exception in thread "main" org.I0Itec.zkclient.exception.ZkException: Unable to connect to master:2181
    at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:66)
so i sub in the IP address of zookeeper into the JSON file and the kafka scheduler is now running.

**Comment by joestein** [comment]
Please change "master" to whatever DNS/IP is routable for your Mesos master. The use of "master" equates to if you were using the vagrant vm https://github.com/mesos/kafka/tree/master/src/vagrant in the project. As far the constraint goes too you can set this to whatever you want that is appropriate for your use cases.

**Comment by batwicket** [comment]
Thanks - that removes a few variables :).
