### ISSUE TITLE
Add option to specify a different port then whatever port --api flag defines

### ISSUE THREAD

**Issue by qvistgaard** [mesos/kafka#176]
This feature could be very useful when running the scheduler inside a docker container, it would be cool if the --api flag works like the LIBPROCESS_ADVERTISE_PORT and LIBPROCESS_ADVERTISE_IP

**Comment by steveniemitz** [comment]
To clarify, are you talking about the resource URLs that are set in the ExecutorInfo, that point back to the scheduler to download the executor jar?

**Comment by qvistgaard** [comment]
I'm closing this, it's i don't believe it relevant anymore
