### ISSUE TITLE
Zookeeper path seems to be ignored

### ISSUE THREAD

**Issue by justizin** [mesos/kafka#178]
In my kafka-mesos.properties, I have configured:

  storage=zk:/mesos-kafka

However, nodes like 'brokers' are created at the root of zookeeper, and while a '/mesos-kafka' node is created, it is empty.

**Comment by joestein** [comment]
that property is for where the scheduler stores it's state, not the zookeeper ensemble for your kafka brokers (fyi). It might be empty from a child znode perspective but should have meta data in the znode if you do a get on the /mesos-kafka znode you have set. To set the kafka brokers zookeeper cluster set the  zk=

**Comment by justizin** [comment]
Thanks for clarifying, this makes complete sense. :)
