### ISSUE TITLE
Add docker support for running executor 

### ISSUE THREAD

**Issue by qianglchina** [mesos/kafka#179]
Hi,
We are running our business all by virtual network in docker, right now mesos slave starts executor just by command, can it be run by docker container?

**Comment by LLParse** [comment]
+1

**Comment by liorze** [comment]
+1. Is there a particular reason that it does not run in a docker container? @joestein, maybe you could help here.

**Comment by krishnabigdata** [comment]
+1, Please let us know when this docker support will be provided, is there any specific reason, this is not provided?

**Comment by steveniemitz** [comment]
I've opened #270 as a catch-all for docker support, closing this one.
