### ISSUE TITLE
Question: How configure the --api scheduler argument ensuring HA?

### ISSUE THREAD

**Issue by azimut** [mesos/kafka#185]
I see that the `--api` argument should be a domain or IP where is the mesos master. But what would happen if that particular mesos master goes down? Would I need to schedule the kafka scheduler on a new master manually? There is a way to ensure HA currently?

**Comment by bwsw** [comment]
API is not for mesos master. It's for framework URL. You can run framework using marathon to get it available.

docker run -d -p 7000:7000 sagent/mesos-kafka scheduler --master=mesos.service.consul:15050 --zk=zookeeper.service.consul:2181 --api=http://mesos.service.consul:7000
