### ISSUE TITLE
Can mesos-kafka support versions newer than 0.8.1.1?

### ISSUE THREAD

**Issue by jholmberg-cni** [mesos/kafka#201]
Hi There,
With great anticipation, I'm interested in deploying Kafka onto our Mesos cluster. I noticed that currently the build.gradle is set to use Kafka 0.8.1.1. 
I'm interested in taking advantage of KafkaConnect, provided in Kafka 0.9. Could this be solved by simply cloning the project and setting the version 0.9?
Thanks in advance for your consideration!
-Jared

**Comment by dmitrypekar** [comment]
Hey, kafka-mesos supports kafka 0.9.
Support was added since 0.9.4.0 - https://github.com/mesos/kafka/releases

You do not need to modify build.gradle.

**Comment by jholmberg-cni** [comment]
Fantastic! Thanks so much for your help!
