### ISSUE TITLE
Property for broker endpoint

### ISSUE THREAD

**Issue by f1yegor** [mesos/kafka#208]
The problem is:
1. in mesos I have resource ports 80, 443, 1000-5000
2. I want to place http service and use ports 80, 443
3. If I start mesos-kafka first, it will occupy first available resource port -> 80

```
{
  "brokers": [
    {
      "task": {
        "endpoint": "do1:80",
        "id": "broker-1-fa84029d-8b35-43de-89f5-0b4594901133",
        "executorId": "broker-1-d7089832-1c29-48e5-b636-abaf8566ac10",
        "slaveId": "26c5379e-227a-41f0-9b80-5d94bda77bbe-S0",
        "state": "running",
        "hostname": "do1"
      }
    }
  ]
}
```

Could it be some option which endpoint port range to use?

**Comment by tpolekhin** [comment]
You can use `--port` option for static port assignment when you create a broker.
If you want a range of port specifically for kafka you should use mesos roles for that

**Comment by f1yegor** [comment]
thanks for reply. will try.

**Comment by tpolekhin** [comment]
Also, i there is a mention in the configuration itself that you can specify port range.
https://github.com/mesos/kafka#adding-brokers-to-the-cluster

```
--port                port or range (31092, 31090..31100). Default - auto
```

never tried this myself but may work
