### ISSUE TITLE
Setting broker attributes

### ISSUE THREAD

**Issue by saxrussell** [mesos/kafka#210]
I've set rack attributes for the Mesos slave in /etc/mesos-slave/attributes, but they're not being added to the brokers according to kafka-mesos.sh broker list. Further, when attempting to follow the syntax in the broker help for using attribute filtering, i get a 400 - invalid broker-expr

I guess I'm just missing something elementary, here. Specifically, how do you add attributes to a broker? Some full command line examples of using attribute filtering would also be useful, since I can't seem to get it right based on the help/readme.

**Comment by krish7919** [comment]
Did you find a way out for this?
