### ISSUE TITLE
Will kafka 0.10.0.0 be supported?

### ISSUE THREAD

**Issue by mindscratch** [mesos/kafka#214]
I'm not aware of any changes in the forthcoming release of Kafka 0.10.0.0, but I thought I'd check to see if the kafka framework is still expected to work with the 0.10.0.0 release.

From conversation in mailing list it's expected to be released this week (possibly today).

**Comment by joestein** [comment]
Hey @mindscratch it is on our near term roadmap to test and (if necessary) fix anything that would prevent folks from also running 0.10 too

**Comment by mindscratch** [comment]
Thanks @joestein.

FWIW I meant to say I am not aware of any changes in 0.10.0.0 that might break the framework.

**Comment by moonkev** [comment]
Just an FYI, we wanted to use this framework but also wanted to take advantage of new features in 0.10.0.0.  There was some significant refactoring done to kafka.utils.ZkUtils.  Mainly it's stateful in that it needs to hold a reference to the zkClient, and thus doesn't take it as parameter to many of its methods anymore.  There were a few other subtle differences.  There was also a StringSerializer class that had it's access modifier changed to private that was needed by a couple test cases.  The actual source code that used to use StringSerializer no longer has to provide but still gets usage of it through the utils class without having to indirectly pass it in (I lazily just threw it in the base test case to get us off the ground).    Working changes can be seen here.

https://github.com/moonkev/kafka-mesos/commit/acc99a2f2eb85f5579b9b214979de927bcad5622

**Comment by justizin** [comment]
As noted in above reference pulled @moonkev's changes into a branch, merged with the latest upstream changes (scala and kafka version are now filled by variables in build.gradle), and am testing for our purposes.  PR #220

**Comment by justizin** [comment]
Update: we're running this in production with no problems.

**Comment by JohnOmernik** [comment]
I would love to see these changes in the master branch and usable for the next release.  Looking at Kafka 10, there are logs of features I'd like to incorporate.   @bitmonk So you are running Kafka 10 with Kafka Mesos in production?  based on the last week any issues?  I am considering doing what you did, but my skills at github are not great :)

**Comment by joestein** [comment]
has anyone tried 0.10 brokers with the existing scheduler? I spoke to this already in #225 some already the brokers should start without issue, if there is and the scheduler needs a patch then we should fix that without breaking 0.8 and 0.9 brokers... if there are new features desired in the scheduler to take advantage of 0.10 then we need todo that in a way that doesn't break 0.8 and 0.9 users, please, thnx

**Comment by JohnOmernik** [comment]
@joestein I just set it up with Kafka 10 and it appears to be working well. No issues starting... (this is with the current code from this repo). Will get back to this thread if I see any issues.

**Comment by mindscratch** [comment]
@JohnOmernik how have things been going?

**Comment by mindscratch** [comment]
@JohnOmernik @joestein any update?
