### ISSUE TITLE
Scheduler takes 100% of cluster resources without running any tasks

### ISSUE THREAD

**Issue by akirillov** [mesos/kafka#224]
![image](https://cloud.githubusercontent.com/assets/1193506/16188071/f74c9ab6-36d3-11e6-9df8-92ca7584d799.png)

This behaviour is non-deterministic and the scheduler releases the resources quickly. The scheduler is executed in Docker and doesn't run any tasks/brokers. After a couple of seconds, the usage is back to normal.

Another thing is, however, that I use specific attributes to mark Kafka-tuned Mesos slaves together with constraints to run the framework so there's no way for it to get 100% of the whole cluster. 

Could it be a Mesos resource usage reporting problem or Docker specifics? Master logs show that the scheduler declines the offers as it is supposed to be because no brokers are executed.

**Comment by akirillov** [comment]
Sorry for messing the things: looks like it was a different framework executed with the same name.

**Comment by krish7919** [comment]
How do you specify with constraints while adding a broker?
I am trying to run kafka on particular tuned ubuntu hosts, but it fails.
