### ISSUE TITLE
eroneous TASK_INVALID

### ISSUE THREAD

**Issue by cliff-ops** [mesos/kafka#226]
Broker fails to start with TASK_INVALID/TASK_ERROR message despite the fact that theres enough resources. Here is the relevant log info from the scheduler:

2016-06-23 21:09:20,243 [Thread-189] INFO  ly.stealth.mesos.kafka.Scheduler$  - [statusUpdate] kafka-0-9254f140-24c2-41e8-b71a-8c5e918e0b0e TASK_ERROR slave:#df-S6 reason:REASON_TASK_INVALID message:Task uses more resources cpus(_):1; mem(_):2048; ports(_):[31000-31000]; disk(logging admin)[broker0:data]:1.536e+06 than available disk(logging, admin)[broker0:/data]:1.536e+06; disk(_):50000; mem(_):192223; ports(_):[31000-32000]; cpus(*):24

**Comment by joestein** [comment]
looks like a disk size issue, the scheduler should be fixed to support what size disk as part of the resources via the CLI that isn't currently an option yet related (if not exactly same) as #225

**Comment by cliff-ops** [comment]
Thanks for the reply. I am using a Mesos persistent volume of type "mount":

http://mesos.apache.org/documentation/latest/multiple-disk/

So it is the entire disk I am allocating to the broker. In this case it a 1.5T SSD. Are you sizing the disk size is too big and thats why the scheduler is rejecting it? Is that the issue? Is there a workaround. This is how I start the broker:

./kafka-mesos.sh broker add 0 --api http://master:7000  --volume broker0

broker0 is persistent volume made up of the 1.5T SSD. There is nothing else on the drive.

In reading #225 you mention that disk size should be set via the cli:
https://github.com/mesos/kafka/blob/master/src/scala/ly/stealth/mesos/kafka/Broker.scala#L153

However I don't see a flag anywhere to specify a size.

**Comment by cliff-ops** [comment]
I updated issue 225, the same issue exists in using the REST API to start a broker with a predefined volume ID. You can add it but it wont start. There doesn't look like an option to specify disk size:

https://github.com/mesos/kafka/blob/master/src/scala/ly/stealth/mesos/kafka/HttpServer.scala#L278-L291

**Comment by cliff-ops** [comment]
Is there any workaround for being able to use --volume?

**Comment by joestein** [comment]
the scheduler will need an update to add the disk size to the API, its a defect.. the scheduler was in product way before the persistent volume was a feature so there seems to be some minor surgery and testing left to make it work correctly

**Comment by cliff-ops** [comment]
I see. Is there a branch I could build from that includes this update to Scheduler.scala? Is there anything I can do to help test?

**Comment by cliff-ops** [comment]
Any update? It looks like there is PR pending that will fix this.

**Comment by lmtjalves** [comment]
I'm not sure but I believe I'm also having the same problem. Anyway, here's the error I'm getting:
`message: "Task uses more resources cpus(kafka, kafka-principal, {resource_id: 839353ba-b183-400f-a529-eed53a0e7385}):1; mem(kafka, kafka-principal, {resource_id: 8a027d22-4f00-4148-9489-fe3934cb296f}):1000; ports(kafka, kafka-principal, {resource_id: c16183e5-0f23-4fd8-9335-1ccc018dc0bd}):[9092-9092]; cpus(kafka, kafka-principal, {resource_id: 98a75b3f-b242-47a7-8bf5-eaf9ea14609a}):0.5; mem(kafka, kafka-principal, {resource_id: 32b57d25-d0e8-47c0-b77d-8e3019962925}):256 than available ports(kafka):[1025-2180, 2182-3887, 3889-5049, 5052-8079, 8082-8180, 8182-32000]; cpus(kafka):2; mem(kafka):2415; disk(*):64283"`

**Comment by cliff-ops** [comment]
That's the same error yes. There's a PR open that looks like it adds the proper volume functionality but its been there for 17 days with no response.
