### ISSUE TITLE
Bad message format (incorrect broker.version.fallback?)

### ISSUE THREAD

**Issue by deric** [mesos/kafka#241]
I'm trying to send a message using `kafkacat`:

```
$ echo "test" | kafkacat -P -b "192.168.1.1:10000" -t testTopic -p 0
%4|1468762178.688|PROTOERR|rdkafka#producer-1| 192.168.1.1:10000/0: Protocol parse failure at rd_kafka_produce_reply_handle:1883 (incorrect broker.version.fallback?)
%4|1468762178.688|PROTOERR|rdkafka#producer-1| 192.168.1.1:10000/0: expected 4 bytes > 0 remaining bytes
%4|1468762178.891|PROTOERR|rdkafka#producer-1| 192.168.1.1:10000/0: Protocol parse failure at rd_kafka_produce_reply_handle:1883 (incorrect broker.version.fallback?)
%4|1468762178.891|PROTOERR|rdkafka#producer-1| 192.168.1.1:10000/0: expected 4 bytes > 0 remaining bytes
%4|1468762178.993|PROTOERR|rdkafka#producer-1| 192.168.1.1:10000/0: Protocol parse failure at rd_kafka_produce_reply_handle:1883 (incorrect broker.version.fallback?)
%4|1468762178.993|PROTOERR|rdkafka#producer-1| 192.168.1.1:10000/0: expected 4 bytes > 0 remaining bytes
% Delivery failed for message: Local: Bad message format
```

I've build a Docker image from github master branch. Currently there's different kafka version in `build.gradle` and `src/docker/build-image.sh` [(8.1.1 vs. 8.2.2.)](https://github.com/mesos/kafka/blob/master/src/docker/build-image.sh#L8). I've tried to use 8.1.1 but without any success.

**Comment by project0** [comment]
@deric which version of kafkacat did you tried? the current release has kafka 0.9 support which is incompatible to 0.8 kafka brokers. I dont think this is a problem of this framework.

**Comment by deric** [comment]
@Project0 Yes, you're right I've tested it on kafka 0.8.1.1, but on 0.9 it works fine. The different version in `build.gradle` was a bit confusing to me until I've realized that the code is not used for brokers at all.
