### ISSUE TITLE
Consistent task name for brokers

### ISSUE THREAD

**Issue by liorze** [mesos/kafka#242]
Hi,

Currently kafka-scheduler create tasks with the following name pattern: "kafka-$id". ($id is the broker id).
This makes it difficult to discover via mesos-dns since now there is a new record for each task.
This ticket proposes to change the task names to a consistent name, e.g. "kafka-executor", for all tasks scheduled by kafka-scheduler. This way, we can discover the brokers using the same host name "kafka-executor.kafka.mesos".

Thanks

**Comment by steveniemitz** [comment]
I'm going to close this as a dupe, as I believe a similar concept is being tracked in #261.
