### ISSUE TITLE
kafka-mesos must be built against the same version of kafka as the brokers are running for topic updates to work

### ISSUE THREAD

**Issue by steveniemitz** [mesos/kafka#248]
I ran into this recently, and maybe its just my fault for not thinking about it much, but if kafka-mesos isn't built against the same version of kafka that the brokers are running (or a similar version? my brokers are using 0.9.0 and I think KM is built against 0.8.2), the topic change notifications don't work.

Maybe its worth documenting somewhere?

**Comment by vidhyaarvind** [comment]
@steveniemitz - I am facing the same issue. Have you tested the code change? Are you running any clusters with your code change? I see you still are using 0.8.2.2

**Comment by steveniemitz** [comment]
I'm running 4 clusters now (2x42, 2x16 nodes) with this change, both on 0.9.0.

**Comment by vidhyaarvind** [comment]
@steveniemitz sounds good. Will try it out
