### ISSUE TITLE
Is this available as package on DCOS?

### ISSUE THREAD

**Issue by sandeepdeva** [mesos/kafka#250]
I was under assumption that https://github.com/mesosphere/dcos-kafka-service is using this project but looks like it does not. I like the API provided by this framework and want to use it on a DCOS cluster, is it available in DCOS as a package? I am new to Mesos/DCOS so I am not sure if this framework can be used on DCOS.

Thanks

**Comment by steveniemitz** [comment]
I'm not very familiar with DCOS, however anything running mesos should be able to run this framework.  I've heard of many people running the scheduler in marathon, and personally I run it in aurora.

**Comment by a-nldisr** [comment]
Mesosphere has created their own version of kafka on their DCOS platform. You can find it here:
https://github.com/mesosphere/dcos-kafka-service

I can confirm Steve that this runs when deploying the scheduler with Aurora.
