### ISSUE TITLE
Swap Usage in Scheduler

### ISSUE THREAD

**Issue by JohnOmernik** [mesos/kafka#255]
Hey all, I am running the kafka-mesos scheduler on a node with 128GB of ram. Right now, there is 60GB free on the node, but when looking at the node, I noticed some swap being used... this confused me... why would it need to use swap? So I did some digging and found this page: http://northernmost.org/blog/find-out-what-is-using-your-swap/  which pointed the finger at a java process... the java process for the kafka-mesos scheduler... This is odd to me... I have plenty of memory, why would it use swap? Is this something Java does? Some Kafka-mesos does? Is it bad? 

Thanks

**Comment by steveniemitz** [comment]
Do you know what the actual working set of the process is/was when you see it using swap space?  I've never actually run the scheduler on a machine with swap enabled, so I can't comment on usage, but I do think I've seen the working set gradually increase over time, which could manifest as swap usage.

Typically swap usage on machines with it enable isn't a bad thing however.
