### ISSUE TITLE
Has this codebase been abandoned?

### ISSUE THREAD

**Issue by clehene** [mesos/kafka#257]
I noticed there's no more activity here, which is unfortunate. 
There are outstanding issues and PRs, however. 
If there's no intent to maintain this any longer, we should make this clear for everyone so that someone could either pick up or otherwise transition to alternatives like https://github.com/mesosphere/dcos-kafka-service.

Ping @joestein, @dmitrypekar

**Comment by miroswan** [comment]
+1

**Comment by jomach** [comment]
+1

**Comment by JohnOmernik** [comment]
I agree with understanding it whether it's abandoned, but dcos-kafka-service isn't a replacement, that requires DCOS... This is a mesos-kafka service.

**Comment by clehene** [comment]
@JohnOmernik I'm not sure if dcos-kafka requires something DCOS specific, it's just that it's the default Kafka scheduler for the DCOS Mesos distro. I can take a deeper look and report back. 
We're still using this one and I wonder why Mesosphere hasn't picked this one too and chose to build another one from scratch, however we need to choose where we spend resources and it's unclear where this one is going.

**Comment by liorze** [comment]
@clehene Mesosphere are using dcos-commons as the basis of their frameworks. I guess that starting from scratch requires the same amount of effort as changing the existing codebase.

**Comment by steveniemitz** [comment]
I'm still actively developing on our fork (https://github.com/tellapart/kafka-mesos/tree/tcdc).  If this has been abandoned I'd be happy to pick it up.

**Comment by mindscratch** [comment]
@joestein is it being baked into the kafka project? https://issues.apache.org/jira/browse/KAFKA-1207

**Comment by steveniemitz** [comment]
That jira ticket is pretty old (almost 3 years now), I think it was made before this project started.

**Comment by mindscratch** [comment]
@steveniemitz agreed, but I had noticed that Jason Gustafson (@hachikuji) updated the "fix version" to 0.10.2.0 a couple months ago, so I thought maybe it was going to make some progress there.

**Comment by hachikuji** [comment]
Before the 0.10.1.0 release, I took a bunch of issues that had been marked for 0.10.1.0, but were not going to get in, and moved them to 0.10.2.0. Guess this was one of them, but unfortunately it's not an indication of progress. Sounds like that ticket may need a new champion.

**Comment by steveniemitz** [comment]
I could take it over but I don't really agree it should be built directly into kafka.  Why is something like this project (or the DCOS version) not sufficient?

In any case, it's unfortunate that this project has been abandoned, I have a lot of contributions sitting around waiting.  Is there anyone other than joe stein with access to this project?

**Comment by JohnOmernik** [comment]
So my thought is this is needed because the DCOS version is a specific install methodology that doesn't always fit everyone. Ideally. There would be a kafka-mesos that would be the base, and then there could be a kafka-dcos that builds off of the kafka-mesos to put the orchestration/api stuff that DCOS is looking for.  DCOS installs can be extremely simplistic and don't deal with "upgrades" or changes to versions of something like Kafka. (Right now, you don't upgrade an instance on DCOS, you uninstall, and then reinstall, that's hard from a upkeep stand point)  I use DCOS, but run with a more robust storage platform, so when I install kafka-mesos, I don't use the DCOS install, but instead use this repo because it gives me the flexibility to orchestrate changing storage locations etc. DCOS doesn't do that... (easily that is)

**Comment by mindscratch** [comment]
I also use this repository, but would like to use one that's being maintained (example: support for kafka 0.10.x). Perhaps @steveniemitz's repo could be the new home (or maybe he could be given access to this one).

**Comment by steveniemitz** [comment]
Agreed, we could make https://github.com/tc-dc/kafka-mesos/tree/tcdc (I recently moved it out of our TellApart repo) the new home, there are a lot of bug fixes in it, as well as support for 0.10.x.  I'd happily accept pull requests as well if people wanted to contribute.

My only worry is about discoverability of that repo.  I guess a big all-caps issue in this one saying "WE'VE MOVED" might be enough?

**Comment by mindscratch** [comment]
@steveniemitz how about submit a pull request to this repo's README that puts a `project status` section at the top that says "we've moved", with a link to the new repo and to this ticket?

**Comment by steveniemitz** [comment]
@mindscratch Heh if I could get a pull request merged we wouldn't be in this situation to begin with 
😰

**Comment by a-nldisr** [comment]
Question: Since Mesos is an Apache project and there are references to apache, would it be possible for an Apache member to step in and transfer ownership when a project is abandoned? I suspect its not possible since this repo is not part of https://github.com/apache, perhaps move this repo there? @joestein @dmitrypekar

**Comment by a-nldisr** [comment]
Had contact with Joe, asked if he would be willing to transfer ownership of the repo. He will follow up in a couple of weeks.

**Comment by steveniemitz** [comment]
Ah amazing!  Thank you!

**Comment by eli-jordan** [comment]
@steveniemitz We are planning to upgrade to kafka 0.10 soon, and evaluating whether we should use your fork.
* How stable / tested is your fork? 
* I see that you have done a large refactor. Are there any backwards incompatible API changes? because we have several tools that use the API.

**Comment by steveniemitz** [comment]
@eli-jordan
Great to hear.  The head of tcdc is generally what we run in production, so it's stable.  As for backwards compatibility, the API is 99% backwards compatible, the only breaking change I can think of is that the topic list JSON now returns an actual array of ints for the replica assignment rather than a string.

**Comment by steveniemitz** [comment]
@a-nldisr any update?

**Comment by a-nldisr** [comment]
Nothing yet, ill contact again.

**Comment by a-nldisr** [comment]
Been in contact, Joe informed me he is not the owner and we should go after the org owner. Suggestion is that a mail should be send to the mailing list.

**Comment by steveniemitz** [comment]
Ah ok, I assume the mesos list?  I know a few people on the mesos side, I can get in touch with them.

**Comment by a-nldisr** [comment]
I suspect the email address listed on the org page: dev@mesos.apache.org

**Comment by steveniemitz** [comment]
👍 I'll try to find someone who can help today.

**Comment by steveniemitz** [comment]
Great success!  Thanks to @a-nldisr and Vinode who helped.  I'll follow up tomorrow with plans on getting everything up to date in here and start getting some of these outstanding pull requests merged.

**Comment by a-nldisr** [comment]
GREAT!

**Comment by steveniemitz** [comment]
I just cut a release of 0.10.0.0-rc0, which incorporates most changes from our fork.  Feel free to try it out!

Also, re: communication, would people be interested in a mailing list or slack channel?  For slack we could just start a channel in the apache mesos slack org.

**Comment by mindscratch** [comment]
I'd prefer a slack channel.

**Comment by steveniemitz** [comment]
Cool, I made a channel #kafka-mesos in the mesos slack (mesos.slack.com), you can make an account for it here: https://mesos-slackin.herokuapp.com/.

I'll update the README as well.
