### ISSUE TITLE
Upgrade to mesos 1.0 libs, use labels on launched executors/tasks

### ISSUE THREAD

**Issue by steveniemitz** [mesos/kafka#261]
Based on the conversation in #216 mesos 1.0 introduced the concept of labels that can be applied to executors and tasks.  We should use this to label launched executors with the broker ID.

**Comment by steveniemitz** [comment]
In addition, we should investigate how to best name executors/tasks to fit the convention things like mesos-dns expect.

**Comment by JustinVenus** [comment]
@steveniemitz fwiw I like the convention aurora uses when filling out DiscoveryInfo.

```json
discovery: {
visibility: "CLUSTER",
name: "packager-brew.staging.nobody",
environment: "staging",
location: "ZeroZero",
ports: {
ports: [
{
number: 31720,
name: "http",
protocol: "TCP"
}
]
}
}
```
