### ISSUE TITLE
[Question] Security features supported?

### ISSUE THREAD

**Issue by renou** [mesos/kafka#268]
Hi!

Are [security features](https://kafka.apache.org/documentation/#security) introduced in Apache Kafka 0.9 supported by the scheduler? It wasn't mentioned in the readme.

Thank you!

**Comment by steveniemitz** [comment]
There isn't, but it shouldn't be too hard to add in.  I'd be happy to review a pull request for it!

**Comment by renou** [comment]
Thank you! Let me take a look :)

**Comment by CBR09** [comment]
@renou , @steveniemitz : what progress on that?, I'm willing to working on that, where should I start?

**Comment by renou** [comment]
@CBR09 I made no progress so far... distracted by other things... :)
