### ISSUE TITLE
Store scheduler state in the state abstraction

### ISSUE THREAD

**Issue by guenter** [mesos/kafka#27]
The framework currently stores its state in a JSON file in the current directory. It should be stored with the Mesos state abstraction for persistence.

**Comment by joestein** [comment]
I just pushed a change that has pluggable cluster storage stat https://github.com/mesos/kafka/blob/master/src/scala/ly/stealth/mesos/kafka/Cluster.scala#L116 so adding http://mesos.apache.org/api/latest/c++/interfaceorg_1_1apache_1_1mesos_1_1state_1_1State.html to be used when "mesos" is in the config for clusterStorage

**Comment by dmitrypekar** [comment]
Storage is switchable. Two storage types are available: file and zk.
I think, that this is exactly what is required by ticket. Closing.
