### ISSUE TITLE
[Question] Mesos version and kafka framework version

### ISSUE THREAD

**Issue by CBR09** [mesos/kafka#273]
Hi everyone,
I want to deploy Kafka on mesos and wonder what version of mesos work well with kafka framework (v0.9.5.1 or v0.10.0.0-rc0)?, any recommendation for production deployment?. I'm also deploy Spark on mesos to processing data. If anyone has production deployment: spark, kafka on mesos, could you show me what versions you are running?, it would really be useful to me.

Thanks in advance

**Comment by steveniemitz** [comment]
I'd recommend using the latest version of mesos you can, but pretty much any version you can find should work fine.  We actually run the scheduler on a 0.22.1 cluster, as well as a bunch of 1.0.2 clusters, but again, I'd highly recommend at least 0.28.0.

**Comment by CBR09** [comment]
Thanks for your recommend, I will use the latest mesos 1.1.0, by the way, how stable is kafka v0.10.0.0-rc0 release?

**Comment by steveniemitz** [comment]
Stable, we've been running it for about a month now in production without issues.  However, #271 was just reported and fixed, I'm about to release rc1 to address it, I'd recommend going to that version.

**Comment by steveniemitz** [comment]
0.10.0.0-rc1 is out now: https://github.com/mesos/kafka/releases

**Comment by CBR09** [comment]
Thank you, your work is amazing.
