### ISSUE TITLE
Launch kafka with docker

### ISSUE THREAD

**Issue by tnachen** [mesos/kafka#28]
Currently in the readme it's required for user to download the kafka jar to run it, but ideally we should support user specifying a docker image to use to launch kafka, and the supported docker options that makes sense for Kafka.

**Comment by dmitrypekar** [comment]
This seems to be implemented. src/docker provides required file to build docker image containing:
ubuntu 14.04, openjdk, kafka distro, kafka-mesos.jar. Which are enough to run kafka-mesos inside docker container. Please reopen, if the above is not true or doesn't meet the initial expectations.
