### ISSUE TITLE
Support for serving a custom JRE is broken

### ISSUE THREAD

**Issue by steveniemitz** [mesos/kafka#280]
Recent JRE distributions (from oracle at least) package the distribution as `jre{version}/bin/java`, but the scheduler assumes `jre/bin/java`.  This causes issues obviously.

**Comment by yu2003w** [comment]
Usually JAVA_HOME is required to be set as jre{version}.
Do we need to fix this problem? As user maybe use openjdk, ibm java and so on, is this a real issue?

**Comment by steveniemitz** [comment]
This isn't referring to a custom JRE installed normally on the host, it's referring to using the `-jre` parameter to the scheduler, which downloads and unpacks a JRE in the broker sandbox before launching it.
