### ISSUE TITLE
Multiple version of kafka same schedular

### ISSUE THREAD

**Issue by veeruns** [mesos/kafka#297]
How would you run multiple version of kafka?

A) I have 2  running clusters, I do not want to change the version on 1 of them, while the other needs to be upgraded.

B) I have 2 running clusters, need to upgrade a broker, Can we do this by changing config of the broker? Can we have schedule a rolling upgrade?

**Comment by steveniemitz** [comment]
The way I've done rolling upgrades in the past has been:
- Start on version A
- Upgrade scheduler to version B
- Restart some subset of brokers, which upgrades them to version B
- Test, etc
- Restart rest of brokers, bringing them to version B.

**Comment by veeruns** [comment]
@steveniemitz 
What if we have multiple clusters running with single scheduler ?
Single scheduler, that manages both clusters, wouldnt be nice if we can selectively point the executor for each cluster?

Cluster A --> v1, Cluster B --> v1, need to upgrade A
