### ISSUE TITLE
More config support for scheduler from Apache Kafka?

### ISSUE THREAD

**Issue by akitekt** [mesos/kafka#308]
It seems the scheduler does not support enough configs like the apache kafka.
Does it mean these options are not supported?

For example, in apache kafka server. properties, you can set :
  | auto.create.topics.enable=false **(Critical for Production usage)**

More options : https://github.com/apache/kafka/blob/trunk/config/server.properties

**Comment by steveniemitz** [comment]
You can set all kafka server properties via `--options`

**Comment by akitekt** [comment]
Hi @steveniemitz 
the scheduler complains with the error below when using --options:
**Exception in thread "main" java.lang.Error:** **options is not a recognized option**
_Here is how i used it:_
/kafka-mesos.sh scheduler --master=xxx --zk=xxx --api=xxx --storage=zk:/kafka-mesos-scheduler --framework-name=kafka --framework-timeout=30d --log=/var/log/kafka-mesos.log --debug=false **--options auto.create.topics.enable=false**

**Comment by akitekt** [comment]
@steveniemitz 
for version,
Kafka Jar: kafka-mesos-0.10.0.0-rc2-kafka_2.10-0.10.1.1.jar

**Comment by steveniemitz** [comment]
I recommend reading the documentation:
https://github.com/mesos/kafka#adding-brokers-to-the-cluster

It's a broker configuration option, you're trying to set it on the scheduler itself.

**Comment by veeruns** [comment]
kafka-mesos.sh broker add 0    --options file:../server.properties

This is what I did

**Comment by akitekt** [comment]
Thanks guys, i was thinking if there is a consistent way to force all brokers to follow the same options.
I think i will use @veeruns solution with versioned properties files for now.
