### ISSUE TITLE
Will Kafka 0.11.x be supported?

### ISSUE THREAD

**Issue by mindscratch** [mesos/kafka#317]
Are there plans to upgrade Kafka to version 0.11.x?

**Comment by steveniemitz** [comment]
Have you tried it?  It should "just work" unless the interfaces changed (again...)

**Comment by mindscratch** [comment]
do I just need to download the latest kafka tar and drop it somewhere? how does the framework find/use it?

**Comment by mindscratch** [comment]
oh I see from the install, gradle is used to d/l kafka :)

**Comment by steveniemitz** [comment]
Yep!  You can also just download it yourself.  I believe the gradle tasks just downloads whichever version is in the gradle build script, but the scheduler will just look for a tar named kafka-* iirc and use whatever it finds.

I recommend building kafka-mesos against the same version of kafka that is being run, but it's not a hard requirement, and certainly fine for testing.

**Comment by mindscratch** [comment]
Are there plans to update the project to be built off the new version and release that?

**Comment by steveniemitz** [comment]
I'd certainly accept a pull request ;)

**Comment by mindscratch** [comment]
That's fair :) ....if I make the changes and I'm able to perform the [install](https://github.com/mesos/kafka#installation) steps successfully, is that good enough to then submit a PR?

**Comment by steveniemitz** [comment]
I think so!  I think all you should need to do is bump the version, and (assuming none of the interfaces changed), copy https://github.com/mesos/kafka/tree/master/src/scala/iface/0_10/ly/stealth/mesos/kafka/interface/impl to 0_11.

edit: and add 0.11 to the travis.yml file too, we can exclude building on JDK 7 though.

**Comment by mindscratch** [comment]
Ok, I will try and do it this weekend. Thanks!

**Comment by rhoml** [comment]
This would be awesome to merge
