### ISSUE TITLE
Kafka command script should conform with DCOS cli style

### ISSUE THREAD

**Issue by tnachen** [mesos/kafka#39]
Currently the flags are defined as:
Usage: {help {command}|status|add|update|remove|start|stop|rebalance}

Since DCOS kafka CLI is calling the jar directly, we want the syntax to conform with the oher services, such as:

`dcos kafka --help`:

dcos kafka status
dcos kafka add
dcos kafka update
dcos kafka remove
dcos kafka start
dcos kafka stop
dcos kafka rebalance

And then each subcommand should support its individual help command
`dcos kafka status --help`

dcos kafka status <options.....>
This returns the status of your kafka brokers, etc....

**Comment by dmitrypekar** [comment]
Fixed. Need to merge following PRs:
https://github.com/mesos/kafka/pull/40
https://github.com/mesosphere/dcos-kafka/pull/2

**Comment by dmitrypekar** [comment]
#40 merged. Should be closed after merging https://github.com/mesosphere/dcos-kafka/pull/2
