### ISSUE TITLE
Ability to specify static service ports for brokers

### ISSUE THREAD

**Issue by JohnOmernik** [mesos/kafka#44]
Since Kafka has gone to a an approach where clients don't use zookeeper to find brokers (this is helpful for Mesos as brokers land on random mesos assigned ports) should the scheduler use marathon or some marathon like setup so we can specify service ports per broker?  With Service ports and something like mesos dns, we'd have a list of static brokerlists we can use with clients, since clients may not be aware of mesos dns, we can't use that for ports (just names) and since we we don't know which ports the broker will land on, the list could change. Right now, I am taking some of my kafka clients and "starting" them by by rewriting my confs on the client each time, not scalable and prone to error.

**Comment by joestein** [comment]
You can call the scheduler https://github.com/mesos/kafka#using-the-rest-api via api/brokers/status and parse the json to find a broker to call for initial bootstrap for your producers/consumers. The REST interface for the scheduler is available through marathon service port (so you can access the scheduler via haproxy) if you launch the scheduler on marathon https://github.com/mesos/kafka/tree/master/src/docker#running-image-in-marathon

Assigning static ports to brokers without having multiple IP available on slaves introduces other issue like only being able to run 1 scheduler per cluster. This might be ok for some folks for some use cases.  In those cases I could see some additional option i.e. "--static-broker-port" when the scheduler starts to "pin" brokers to a port via the scheduler (and the same port for each broker) but would not encourage that though not opposed to supporting it.

We could also maybe have the scheduler respond like the brokers do on producer/consumer startup with a valid/live MetadataResponse https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-MetadataResponse . Producers and Consumers would then just need to hit the scheduler (which they could do via haproxy) and no other changes at all. This has possibly some more nuances though we have been talking about making the scheduler be more like a broker (especially in terms of the controller) so there are more possible benefits going down that path.

Let me know if you still need static ports, if the existing dynamic discovery works as it is now works for you, if the scheduler responding like if it was a broker for Metadataresponse would be necessary or something else?

**Comment by JohnOmernik** [comment]
Since originally posting this, I have found the Kafka Rest API from Confluent.  While this still may be an issue for some, I think it poses less of an issue. There are also API ways to address broker location in Kafka Rest.  The issues I was having was in using pre created topologies that expected  brokers hard coded and worried about using these with brokers that moved. If I am creating my own interfaces, I can address the broker locations programmatically.  That may make portability on topologies or other interfaces to kafka less portable (those created for straight kafka, won't work without modification) but should be adjustable on a case-by-base basis.  I think it's still a concern, however, I see your points on challenges in the static ports.

**Comment by sybrandy** [comment]
Along the same lines, could there be an option to restrict the dynamic ports to a specified range?  This would be useful for environments where iptables is heavily used so we want to restrict the number of potential open ports to a fixed range.

**Comment by JohnOmernik** [comment]
sybrandy -

That makes sense to me, it would allow a bit of flexibility while making
some admin tasks easier.

**Comment by y4roslav** [comment]
Totally agree with @sybrandy about "restrict the dynamic ports to a specified range". That real pain right now for our clusters. Would be great to have such options. +1 for that.

**Comment by joestein** [comment]
You can do that now. You have to setup a role and on the slave ports are a resource, give whatever ports you want to that role, then bind kafka framework to that role. Kafka frameworks runs on whatever ports is offered by from the slaves.

**Comment by JohnOmernik** [comment]
Interesting, lots can be done with that to ensure a static port and/or make
it so one broker per node exists... just specify a port outside the normal
ports range as only allocated to the kafka brokers role.  Thank Joe.

**Comment by y4roslav** [comment]
@joestein I have few problems: 
1. I'm not very familiar with mesos roles and documentation is not very comprehensive about it. 
2. As far as I understand framework should be able to support it, doesn't it? 

Can somebody just point me to documentation or some examples?

**Comment by joestein** [comment]
--framework-role https://github.com/mesos/kafka#scheduler-configuration on the kafka side

on slave http://mesos.apache.org/documentation/latest/configuration/  --resources=VALUE  
Total consumable resources per slave, in the form
name(role):value;name(role):value...

**Comment by dmitrypekar** [comment]
Added PR for this feature - https://github.com/mesos/kafka/pull/52
Could be closed after the merge.

**Comment by joestein** [comment]
merged
