### ISSUE TITLE
gradlew fails on centos 7

### ISSUE THREAD

**Issue by machinethinking** [mesos/kafka#50]
Using gradle 2.4, Centos 7 with most recent updated packages.

$ ./gradlew jar --debug
...
16:22:50.927 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac] ly/stealth/mesos/kafka/Scheduler.scala
16:22:50.928 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac] ly/stealth/mesos/kafka/Util.scala
16:22:51.050 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac] Scalac params = ''
16:22:59.911 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac] /root/gradle/kafka/src/scala/ly/stealth/mesos/kafka/BrokerServer.scala:110: error: not found: value getClassLoadingLock
16:22:59.912 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac]       getClassLoadingLock(name) synchronized {
16:22:59.912 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac]       ^
16:23:02.469 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac] warning: Class java.lang.AutoCloseable not found - continuing with a stub.
16:23:02.470 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac] error: error while loading NetworkConnector, class file '/root/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-server/9.0.4.v20130625/64ac312bb641da49c73491e8c176bc1efdcd3857/jetty-server-9.0.4.v20130625.jar(org/eclipse/jetty/server/NetworkConnector.class)' is broken
16:23:02.470 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac](class java.lang.NullPointerException/null)
16:23:05.271 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac] /root/gradle/kafka/src/scala/ly/stealth/mesos/kafka/Util.scala:134: error: value inheritIO is not a member of ProcessBuilder
16:23:05.272 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac] possible cause: maybe a semicolon is missing before `value inheritIO'?
16:23:05.272 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac]         .inheritIO().redirectOutput(file).start().waitFor()
16:23:05.272 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac]          ^
16:23:05.573 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac] one warning found
16:23:05.574 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:scalac] three errors found
16:23:05.575 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':compileScala'
16:23:05.575 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :compileScala FAILED
16:23:05.593 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :compileScala (Thread[main,5,main]) completed. Took 17.373 secs.
16:23:05.594 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 17.452 secs, idle: 0.014 secs

**Comment by dmitrypekar** [comment]
What version of JDK is used to build?
Could you please provide the output of `java -version`?

**Comment by machinethinking** [comment]
Let me know if there's anything else I can get for you:

 # java -version
java version "1.6.0_35"
OpenJDK Runtime Environment (IcedTea6 1.13.7) (rhel-1.13.7.1.el7_1-x86_64)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

 # rpm -qa | grep jdk
java-1.6.0-openjdk-devel-1.6.0.35-1.13.7.1.el7_1.x86_64
java-1.6.0-openjdk-1.6.0.35-1.13.7.1.el7_1.x86_64

**Comment by dmitrypekar** [comment]
You need java 7 or higher to build kafka-mesos. Could you upgrade to openjdk-7 and try to rebuild?

**Comment by machinethinking** [comment]
That did work and I can start the scheduler, thank you! Still having problems getting the brokers started but still investigating that.
