### ISSUE TITLE
We should provide a more configurable override for the log4j.properties in the broker

### ISSUE THREAD

**Issue by joestein** [mesos/kafka#54]
Changing the settings for the log4j properties currently requires packing up another tgz, stop, copy tgz to uri server, start in order to use. This could be further automated from the command line specifying this file. We should also have some of the options work from the command line that can filter down. We should share this also with the scheduler and make it easily modifiable.

**Comment by dmitrypekar** [comment]
Created PR - broker_log4j_config.
Please review and merge.
