### ISSUE TITLE
Document LIBPROCESS_PORT

### ISSUE THREAD

**Issue by sybrandy** [mesos/kafka#55]
Perhaps this is fairly common knowledge, but could the fact that you can set the LIBPROCESS_PORT to communicate with mesos be documented?  It took a while for me to track down a communication issue because I didn't realize that this port was being opened.  I only tried it because one of my coworkers suggested it since we had to do the same thing for Chronos.

**Comment by dmitrypekar** [comment]
I am not sure, that this should be a part of documentation for kafka-mesos. This point seems to be generic to any Mesos cluster.
