### ISSUE TITLE
Set the broker's zookeeper chroot path

### ISSUE THREAD

**Issue by dlaidlaw** [mesos/kafka#56]
There should be a method to set the chroot path when the brokers use zookeeper. This is normally appended to the zookeeper.connect configuration property.

**Comment by dmitrypekar** [comment]
Hi. This is already supported by --zk option of the scheduler. It is passed as is to Kafka brokers as 'zookeeer.connect' option. So it could be specified like: "zk=master:2181/abc" including chroot path.

Please confirm, is that exactly what was required?

**Comment by dlaidlaw** [comment]
That is exactly what I want. Nice.
