### ISSUE TITLE
kafka-mesos.sh doesn't work and API does

### ISSUE THREAD

**Issue by y4roslav** [mesos/kafka#63]
I know that it is some misconfiguration but I don't see which.

REST API 
Add:

```
[centos@host-04 kafka-mesos]$ curl http://kafka-mesos-scheduler.service.consul:7000/api/brokers/add?id=0
{"brokers" : [{"id" : "0", "mem" : 128, "cpus" : 0.5, "heap" : 128, "failover" : {"delay" : "10s", "maxDelay" : "60s"}, "active" : false}]}
```

Start:

```
 [centos@host-04 kafka-mesos]$ curl http://kafka-mesos-  scheduler.service.consul:7000/api/brokers/start?id=0
   {"status" : "started", "ids" : "0"}
```

Status: 

```
[centos@host-04 kafka-mesos]$ curl http://kafka-mesos-scheduler.service.consul:7000/api/brokers/status?id=0
 {"brokers" : [{"task" : {"hostname" : "host-05", "state" : "running", "slaveId" : "20150625-135133   -2919893514-15050-12781-S0", "executorId" : "broker-0-99345375-fca8-4340-9a0b-e04fb25ae934",   "attributes" : {"node_id" : "host-05"}, "id" : "broker-0-3a671b4e-ee59-4b2a-a
```

In case of kafka-mesos.sh 

```
[centos@host-04 kafka-mesos]$ kafka-mesos.sh add 1
Error: java.io.IOException: 405 - HTTP method POST is not supported by this URL
[centos@host-04 kafka-mesos]$ kafka-mesos.sh status
Error: java.io.IOException: 405 - HTTP method POST is not supported by this URL
 [centos@host-04 kafka-mesos]$ kafka-mesos.sh status --api http://kafka-mesos-scheduler.service.consul:7000
 Error: java.io.IOException: 405 - HTTP method POST is not supported by this URL
```

My `kafka-mesos.properties`: 

```
debug=False
storage=zk:/kafka-mesos
master=zk://zookeeper.service.consul:2181/mesos
zk=zookeeper.service.consul:2181
api=http://kafka-mesos-scheduler.service.consul:7000
```

What did I miss?

**Comment by dmitrypekar** [comment]
It seems that you are using new build of CLI but old build of the Scheduler. The previous build didn't supported receiving requests via POST (only GET was supported). Recently CLI and Scheduler were updated to use POSTs (GETs are still supported, but request size from CLI sometimes is bigger than 4k, so need to use POST). Could you please try to restart a Scheduler using new version of jar?

If this is not the issue we need to investigate it in more details.

**Comment by y4roslav** [comment]
Looks like it is a case. I'm using docker container for scheduler. Can you point me to your official docker container for kafka-mesos scheduler if such exist?

**Comment by dmitrypekar** [comment]
As for now there is no official docker container we maintain. You probably will need to rebuild your docker image to include new jar version.

**Comment by y4roslav** [comment]
Small update

Client version: 

```
kafka-mesos-0.9.1.0.jar
```

Docker container: 

```
https://registry.hub.docker.com/u/y4rv1k/kafka/ 
```

Build on the same `jar` and I have the same error. 

Have any ideas?

**Comment by joestein** [comment]
@Y4Rv1K are you still having issues? 0.9.1.1 is released. If you are having specific error please post.

**Comment by y4roslav** [comment]
Actually issue can be closed. All works after updates
