### ISSUE TITLE
Lost broker attempts to restart on a node with an existing broker on it.

### ISSUE THREAD

**Issue by sybrandy** [mesos/kafka#66]
Hello,

I ran into an interesting situation today doing some testing where I killed a broker expecting it to restart.  However, for a number of attempts it tired to restart on a node that already had a running broker on it.  This behaviour seems counter-intuitive since all of the brokers use the same configuration for where the data directory exists, so knowing that my thought was that it should be restarted on a node that isn't running a broker.

Is there a way to prevent this from occurring?  I didn't see anything in the docs, but there's always the chance I missed something.

**Comment by dmitrypekar** [comment]
Hi.
You can use --constraints option for restricting the slaves where brokers are started.
Please see `./kafka-mesos.sh help update` for more details.
Seems, that you can use `unique` constraint in your case.

**Comment by sybrandy** [comment]
Ah, thanks.  That looks like it should work.  Just out of curiosity, any reason why this isn't the default behaviour for Kafka?  Unless I specify that each broker has it's own data directory, the current behaviour doesn't make much sense to me.  Also, I'm not really sure if having multiple brokers on one node is a good idea.
