### ISSUE TITLE
There is no way to set the JMX port

### ISSUE THREAD

**Issue by joestein** [mesos/kafka#69]
This sometimes desired. Sometimes it should be dynamic and sometimes static.

So, please keep the existing functionality, allow for dynamic assignment of the port and an ovverride for static assignment. The JMX_PORT is set prior to kafka starting up (e.g. JMX_PORT=./kafka-server....)

**Comment by abiletskyi** [comment]
I was able to set jmx port through jvm-options parameter. Using CLI: 

#./kafka-mesos.sh add 1 --jvm-options "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

#./kafka-mesos start 1

Then you can check with jconsole you can connect to <host>:9010 to access metrics.

**Comment by KevinJMao** [comment]
Note that JMX opens a second port where RMI remote object stubs are served out of. By default, this port is dynamically allocated to a high-order port. In order to make it static, you can pass in this parameter: `-Dcom.sun.management.jmxremote.rmi.port=9998`

**Comment by dmitrypekar** [comment]
@abiletskyi thanks.
It seems that this requirement could be archived by using `jvm-options` option.
@joestein imho, we should not add additional options to add|update commands for this,
may be only add a new section to README.md. What do you think?

**Comment by memelet** [comment]
Can using --jvm-options work with kafka-manager which wants JMX_PORT to be set?
