### ISSUE TITLE
broker placement stickyness for slave failure

### ISSUE THREAD

**Issue by joestein** [mesos/kafka#70]
We need a way so that if a slave dies (e.g. kernel panic) and reboots there is a time window that if the slave comes back within that window of time it will get replaced on the same broker. If the window has passed (meaning the operator has deemed the failure time long enough) that the broker will get scheduled on another slave.  We should also please cleanup the readme for the existing failover timeouts calling them for the broker failures and having continued failures when launching on the slave before moving to another.

**Comment by dmitrypekar** [comment]
Created PR https://github.com/mesos/kafka/pull/74
Please merge & closed.
