### ISSUE TITLE
We should have more metrics

### ISSUE THREAD

**Issue by joestein** [mesos/kafka#77]
We should first work on places like onBrokerStopped and such. It might be better to use Yammer metrics until the Kafka brokers move over to the Kafka Metrics in the client. We could also consider just writing these to Kafka directly.

**Comment by joestein** [comment]
It might even be good for the kafka scheduler to have its own topic that folks can configure so that information related can be consumed and produce. This would also help the scheduler know if the problem with a broker is wring to it vs another broker and/or another partition, etc.

**Comment by dmitrypekar** [comment]
Closing as outdated. From the moment this issue is opened, we have added few metrics.
For now a ticket about more concrete missing metrics should be created if required.
