### ISSUE TITLE
Kafka repeatedly failing healthcheck

### ISSUE THREAD

**Issue by john-dodson** [mesos/kafka#78]
Every time I launch the kafka package it fails the healthcheck and there is no information as to why in the logs.

**Comment by john-dodson** [comment]
I've gone onto the mesos slaves running the process and am unable to curl the port that kafka is running on, and nothing pertaining to the get request shows up in the logs for the task.

**Comment by john-dodson** [comment]
It turns out this is specific to instance types. For some reason Kafka launches fine on m3.xlarge DCOS slave instances, but the healthcheck is unreachable and times out on r3.8xlarge DCOS instances.

**Comment by joestein** [comment]
Hey @john-dodson this was resolved in #58 the problem was related to the number of acceptor thread jetty was setting by default was based on number of processors. The thread pool was also default so the situation becomes only acceptor and no worker threads.

**Comment by john-dodson** [comment]
So if the the Mesosphere DCOS guys build a new jar and update their config the issue should be resolved, correct?

**Comment by tnachen** [comment]
@john-dodson that sounds like so, @joestein are you able to publish a new jar on universe yourself or do you need us to?

**Comment by joestein** [comment]
@dmitrypekar is working on the pr for the universe changes today. I already pushed the jar to s3 or we can use the one from the tag release https://github.com/mesos/kafka/releases/tag/0.9.1.1

**Comment by dmitrypekar** [comment]
Pushed PR to universe: https://github.com/mesosphere/universe/pull/179
It will update kafka-mesos jar to 0.9.1.1 version

**Comment by dmitrypekar** [comment]
@john-dodson Is the problem fixed? Could the issue be closed?

**Comment by joestein** [comment]
@john-dodson please re-open if you are still having issue but this should be resolved now, thanks.
