### ISSUE TITLE
we need a bind address for the scheduler also

### ISSUE THREAD

**Issue by joestein** [mesos/kafka#81]
As we are doing with brokers, schedulers are failing health check because the ip to bind too is the ip of the offer which is not routable for the services (just the master and slaves). We need to set a bind address for the scheduler. When we do this now moving forward the brokers should inherit that setting and have the ability to override it please.

**Comment by dmitrypekar** [comment]
Will be fixed after merging of https://github.com/mesos/kafka/pull/83
