### ISSUE TITLE
question: What are you doing for storage?

### ISSUE THREAD

**Issue by memelet** [mesos/kafka#84]
I would like to run kafka in our mesos cluster, but it typically won't run on every node. In that case, what strategies for storage are being employed? Just give each slave a dedicated disk for kafka? Limit kafka to only run on some nodes with kafka disks? If a kafka is (re)started on a node that previous ran a kafka, how will that disk affect the new kafka?

**Comment by dmitrypekar** [comment]
You can use following strategies depending on your cluster configuration:
1. use constraints to limit brokers to use specific nodes with dedicated locations for data;
2. use dedicated mounted volume for all kafka-aware slaves;
3. some combination of 1&2

**Comment by memelet** [comment]
thanks @dmitrypekar
