### ISSUE TITLE
assigning specific port to brokers

### ISSUE THREAD

**Issue by vidhyaarvind** [mesos/kafka#86]
when I tried assigning specific port to broker it failed and declined my offer. port ranges work
port=9092 did not work
port=31000..32000 worked

2015-07-22 16:03:07,015 [Thread-207] INFO  ly.stealth.mesos.kafka.Scheduler$  - Declined offers:
52.2.20.235#19580 - broker 1: no suitable port
52.6.91.141#19581 - broker 1: no suitable port
52.4.227.57#19582 - broker 1: no suitable port

**Comment by dmitrypekar** [comment]
It seems that your mesos slaves doesn't allow (send) 9092 port in their
offers. Please configure your slaves, adding that port.

**Comment by dmitrypekar** [comment]
Closing this as not actual.
`52.2.20.235#19580 - broker 1: no suitable port` message 100% means that offer doesn't contain 9092 port. So this is problem of mesos slave configuration.
