### ISSUE TITLE
Lost scheduler/Broker

### ISSUE THREAD

**Issue by vidhyaarvind** [mesos/kafka#91]
1. When the slave machine running the scheduler is taken out of the cluster or stops responding. The scheduler is not restarted by marathon and it hangs indefinitely.  Attaching image. Destroy /scale up down does not work as well.
   <img width="1434" alt="screen shot 2015-07-31 at 10 23 10 am" src="https://cloud.githubusercontent.com/assets/3187915/9013065/993d7180-376e-11e5-96e3-4917012808cd.png">
   <img width="1245" alt="screen shot 2015-07-31 at 10 22 50 am" src="https://cloud.githubusercontent.com/assets/3187915/9013070/9c1a9e50-376e-11e5-8f2a-d3dc4ed3534d.png">
2. When the slave machine running broker is taken out of the cluster or stops responding. I see Broker Lost message but it's not scheduled in another machine or stopped. scheduler still shows broker is active

**Comment by dmitrypekar** [comment]
Regarding point 2. The designed behavior is in case of broker failure (which actually is modelled) try to reuse same slave node during configurable period of time (--stickyness-period option). After that time is passed Scheduler would restart broker on any matched node. You can find more information here: https://github.com/mesos/kafka/#failed-broker-recovery

**Comment by dmitrypekar** [comment]
Regarding point 1. Described case is 99% not related to kafka mesos, but is related to Marathon / app configuration. Could you please post your app configuration here?

**Comment by serejja** [comment]
One more comment about point 1 - I was just able to run a scheduler on a slave and then tried 2 options:
- shutdown that slave machine completely: Mesos/Marathon noticed the slave went down, healthchecks weren't passing and after ~3-5 minutes tasks/instances count went to 0/1. After I spinned up that machine again Marathon was able to recover (reschedule) the task in another 3-5 minutes.
- turn off networking on the slave machine (via `ifconfig eth1 down`): again Mesos/Marathon noticed the slave went down, the healthchecks weren't passing, but the scheduler was still running on that slave. After I enabled the networking back Marathon was able to recover the scheduler (not sure though did it kill the previous one and started a new instance or recovered the old one).

Can you please post the json you feed to marathon so we can try/figure out more things? Thanks!

**Comment by vidhyaarvind** [comment]
Sorry looks like I missed all these updates. I went ahead and restart all masters and all marathon and everything came back and scheduler started appearing without me adding scheduler again. Looks to me as marathon issue
