### ISSUE TITLE
Kafka brokers are getting lost

### ISSUE THREAD

**Issue by echinthaka** [mesos/kafka#94]
I'm trying to run Kafka scheduler within Marathon with the following job description. I was able to get the scheduler working but the brokers come up but keep getting lost (as seen in the scheduler log and mesos dashboard). What am I doing wrong here. Please note that in my cluster, mesos-master node will never run mesos-slave role. 

```
{
  "id": "/platform/kafka",
  "instances": 1, 
  "cpus": 2,
  "mem": 2048,
  "ports": [8000],
  "container": {
        "type": "DOCKER",
        "docker": {
            "image": "private-registry/kafka-mesos:201508032203",
            "forcePullImage": true,
            "network": "HOST"
        }
  },  
  "healthChecks": [
    {"path": "/api", "protocol": "HTTP"}
  ],
 "env": {
        "MESOS_NATIVE_JAVA_LIBRARY": "/usr/local/lib/libmesos.so"
  },
  "cmd": "cd /kafka-mesos && ./kafka-mesos.sh scheduler --storage zk:/mesos-kafka --master zk://<zk-node>:2181/mesos --zk <zk-node>:2181 --api http://$HOSTNAME:8000"
}
```

Also, the instructions (here)[https://github.com/mesos/kafka/tree/master/src/docker#running-image-in-marathon] suggests to set the api as `master:7000` but I can not do it since I don't have mesos running as a slave too in mesos master node. Hence, I had to use `$HOSTNAME` to get the slave this will get scheduled. 

Really appreciate if someone can help to fix this issue.

**Comment by joestein** [comment]
Hey @echinthaka what version are you using? Can you try to curl the rest end point? It could be the end point hostname is not routable (like if your slaves are on public ip vs internal ip in which case you need to use bind-address).

Also, your health check end points are wrong you should use /health e.g. https://github.com/mesosphere/universe/blob/version-1.x/repo/packages/K/kafka/0/marathon.json#L12 and /api/brokers/status https://github.com/mesosphere/universe/blob/version-1.x/repo/packages/K/kafka/0/marathon.json#L21

**Comment by joestein** [comment]
I re-read your problem "broker come up but keep getting lost ", can you define what you meant here? Can you post an error from the sanbox for why the broker failed?

I got confused with the scheduler running on marathon issue/question which is VERY different than the brokers running so my explanation above could be relevant though it shouldn't affect your brokers unless marathon happens to be killing the scheduler before the brokers are launched or failing over longer than the failover period (not re-registering within it though the default timeout is like 30 days).

Also "LOST" is different than "KILLED" the latter being more likely a scheduler issue i.e. the brokers framework timeout exceeding vs the former i.e. can't bind to host ... Can you please get logs from the sandbox in either case should have more information to diagnose.

**Comment by echinthaka** [comment]
> I re-read your problem "broker come up but keep getting lost ", can you define what you meant here? 

As you can see in the below screenshots, the scheduler comes up and try to schedule the brokers. Brokers get scheduled in mesos but they die immediately with the status set to "LOST". I _think_ the brokers, when they come up, can not contact the scheduler.

Can you please check whether what I pass for `--api` is correct in my job description? The documentation says it should be `master:7000` but in my case it doesn't makes sense coz the scheduler won't come inside the master node (and yes, I had to remove that constraint in the job definition)

Here[1] is what I see in the kafka scheduler logs. The broker logs are empty and here[2] is what I see on mesos dashboard

Thanks for your help @joestein 

[1]

```
disk1-dev-mesos-slave.example.com#23036 cpus:9.00 mem:60744.00 disk:773524.00 ports:[31399..31715][31717..32000][31000..31397]
2015-08-04 01:11:26,246 [Thread-31] INFO  ly.stealth.mesos.kafka.Scheduler$  - Starting broker 2: launching task broker-2-c1c230bf-ded5-41cc-9480-d56bfecb2ef2 by offer disk1-dev-mesos-slave.example.com#23036
 broker-2-c1c230bf-ded5-41cc-9480-d56bfecb2ef2 slave:#36-S0 cpus:2.00 mem:2000.00 ports:[31399..31399] data:defaults=broker.id\=2\,log.dirs\=kafka-logs\,port\=31399\,zookeeper.connect\=disk1-dev-zk.example.com:2181\,host.name\=disk1-dev-mesos-slave.example.com\,log.retention.bytes\=10737418240,broker={"stickiness" : {"period" : "10m"\, "stopTime" : "2015-08-03 22:59:01.619"}\, "id" : "2"\, "mem" : 2000\, "cpus" : 2.0\, "heap" : 1024\, "failover" : {"delay" : "1m"\, "maxDelay" : "10m"\, "failures" : 4\, "failureTime" : "2015-08-03 23:06:12.917"}\, "active" : true}
2015-08-04 01:11:26,539 [Thread-33] INFO  ly.stealth.mesos.kafka.Scheduler$  - [statusUpdate] broker-2-c1c230bf-ded5-41cc-9480-d56bfecb2ef2 TASK_LOST slave:#36-S0 reason:REASON_EXECUTOR_TERMINATED message:Executor terminated
2015-08-04 01:11:26,540 [Thread-33] INFO  ly.stealth.mesos.kafka.Scheduler$  - Broker 2 failed 5, waiting 10m, next start ~ 2015-08-04 01:21:26Z
2015-08-04 01:11:27,240 [Thread-35] INFO  ly.stealth.mesos.kafka.Scheduler$  - [resourceOffers]
disk1-dev-mesos-slave.example.com#23037 cpus:9.00 mem:60744.00 disk:773524.00 ports:[31717..32000][31000..31397][31399..31715]
2015-08-04 01:11:27,246 [Thread-35] INFO  ly.stealth.mesos.kafka.Scheduler$  - Starting broker 1: launching task broker-1-7db3a582-b13c-4c21-8654-ba3e31c38c7d by offer disk1-dev-mesos-slave.example.com#23037
 broker-1-7db3a582-b13c-4c21-8654-ba3e31c38c7d slave:#36-S0 cpus:2.00 mem:2000.00 ports:[31717..31717] data:defaults=broker.id\=1\,log.dirs\=kafka-logs\,port\=31717\,zookeeper.connect\=disk1-dev-zk.example.com:2181\,host.name\=disk1-dev-mesos-slave.example.com\,log.retention.bytes\=10737418240,broker={"stickiness" : {"period" : "10m"\, "stopTime" : "2015-08-03 22:59:02.483"}\, "id" : "1"\, "mem" : 2000\, "cpus" : 2.0\, "heap" : 1024\, "failover" : {"delay" : "1m"\, "maxDelay" : "10m"\, "failures" : 4\, "failureTime" : "2015-08-03 23:06:13.918"}\, "active" : true}
2015-08-04 01:11:27,446 [Thread-37] INFO  ly.stealth.mesos.kafka.Scheduler$  - [statusUpdate] broker-1-7db3a582-b13c-4c21-8654-ba3e31c38c7d TASK_LOST slave:#36-S0 reason:REASON_EXECUTOR_TERMINATED message:Executor terminated
2015-08-04 01:11:27,446 [Thread-37] INFO  ly.stealth.mesos.kafka.Scheduler$  - Broker 1 failed 5, waiting 10m, next start ~ 2015-08-04 01:21:27Z
2015-08-04 01:11:28,241 [Thread-39] INFO  ly.stealth.mesos.kafka.Scheduler$  - [resourceOffers]
```

[2]
<img width="591" alt="screen shot 2015-08-03 at 6 17 56 pm" src="https://cloud.githubusercontent.com/assets/1459631/9051206/32b8e002-3a0c-11e5-840c-9a94a8c1ca1c.png">

**Comment by joestein** [comment]
Your api call should be $HOST:8000 so that whatever slave it runs on is the host set for the api. You can also do $HOST:$PORT0 with [0] as your Marathon port for dynamic assigment. 

Need to see the sandbox log of the lost broker failing.

**Comment by echinthaka** [comment]
@joestein I just changed `$HOSTNAME:8000` to `$HOST:8000` and re-deployed it. But I still see the same issue. Unfortunately there aren't any logs on broker. Here is what I see there. Is there another way to see whats going on?

<img width="1192" alt="screen shot 2015-08-04 at 10 48 36 am" src="https://cloud.githubusercontent.com/assets/1459631/9068226/0dc1e5a6-3a97-11e5-88ea-ba67880f4a2f.png">

**Comment by joestein** [comment]
Can you please check the logs on the slave that this was on and see if there are any errors or something meaningful for this task please.

**Comment by dmitrypekar** [comment]
Can you please check logs /var/log/syslog on host on which broker is lost? It could be that there is some mesos-related error, like failed to chown sandbox directory or some other.

**Comment by echinthaka** [comment]
@dmitrypekar you are correct. I can see `Failed to chown work directory` in the logs. 

on `/var/log/mesos/mesos-slave.ERROR` I see the following.

```
E0804 19:59:57.072525 192845 slave.cpp:3112] Container 'd874a141-ee5b-4a6d-a208-99579cf66a50' for executor 'broker-2-b7b1509d-1143-4343-8639-503c625e161f' of framework '20150729-190149-4076896266-5050-164736-0000' failed to start: Failed to execute mesos-fetcher: Failed to chown work directory
E0804 19:59:57.130091 192841 slave.cpp:3461] Failed to unmonitor container for executor broker-2-b7b1509d-1143-4343-8639-503c625e161f of framework 20150729-190149-4076896266-5050-164736-0000: Not monitored
```

I guess this says the user we are trying to launch these tasks does not have enough privileges. 

In `Frameworks` tab in Mesos dashboard. I see `vagrant` as the user for Kafka framework. Not sure how this user was determined since I never passed that in. 

Then, in the Marathon job description, I passed `--user root`. That didn't change anything. Then I passed in `--principal root` but that was throwing the following error in the logs. 

```
Failed to update resources for container 93efe77b-ad9b-4669-b8b8-c914e71b5bcf of executor platform_kafka.9524762f-3ae3-11e5-afab-00163e3c5222 running task platform_kafka.9524762f-3ae3-11e5-afab-00163e3c5222 on status update for terminal task, destroying container: Failed to determine cgroup for the 'cpu' subsystem: Failed to read /proc/101533/cgroup: Failed to open file '/proc/101533/cgroup': No such file or directory
```

**Comment by dmitrypekar** [comment]
Mesos has known issue, then passing framework-user has no effect if framework (scheduler) is already registered. You can either shutdown a framework using mesos API and remove framework id from kafka-mesos.json (or zk node, if using) and then pass a new user (will register new framework-id) . Alternatively you can specify --no-switch_user on each mesos slave. 

And, probably, passing 'root' as mesos user is not a good idea.

**Comment by echinthaka** [comment]
setting `--no-switch_user` made it work. Thanks @dmitrypekar and @joestein 

If it helps, I can submit a PR to improve the documentation.
