### ISSUE TITLE
Support offers containing several resources with the same name (cpus, mem, etc) and different role 

### ISSUE THREAD

**Issue by dmitrypekar** [mesos/kafka#98]
If not using roles, mesos offer contains single resource for each name (cpus, mem, etc). But if using roles it could contain duplicated resources:

```
master#-O574 cpus:0.30 cpus(kafka):0.70 mem:50.00 mem(kafka):100.00 disk:35164.00 ports:[31000..32000]
```

This should be supported in:
1. ly.stealth.mesos.kafka.Broker#matches
2. org.apache.mesos.Protos.TaskInfo.Builder#addResources(org.apache.mesos.Protos.Resource.Builder)
as mentioned in https://github.com/mesos/kafka/pull/92
3. ly.stealth.mesos.kafka.Util.Str#resources

Unit test for Broker.matches should be modified to cover this case.

**Comment by potto007** [comment]
@dmitrypekar I am going to take a stab at this if it's ok by you.

**Comment by dmitrypekar** [comment]
Sure, please go ahead.

**Comment by joestein** [comment]
Hey @potto007 how are you making out? this is becoming a blocker and is going to take @dmitrypekar a day or two but if you are done or almost done otherwise we need to start the work

**Comment by potto007** [comment]
Hey @joestein, good to hear from you, it's been a while. :) WRT this issue, I got held up by a couple issues with [Druid](http://druid.io) that I've since patched, I hope to have this ready now in the next day or two.

**Comment by dmitrypekar** [comment]
Hey @potto007, probably I will deliver this today, because we need it urgently. Sorry for overlapping.

**Comment by potto007** [comment]
No worries @dmitrypekar - I'll be happy to have the ability regardless. Thanks for letting me know. I'll find something else to tinker with.

**Comment by dmitrypekar** [comment]
PR created.
https://github.com/mesos/kafka/pull/103

**Comment by dmitrypekar** [comment]
PR is already merged. Closing this.
